"""A4 infrastructure contracts and immutable experiment-plan records.

The A4 namespace is intentionally separate from the legacy V0 records and
from the frozen A0--A3 runtime contracts.  This package contains pure data
validation, identity construction, source-free pose planning,
geometry-legality annotation, and motion-budget computation.  It does not
render audio, run ASR, or choose experimental geometries.
"""

from active_audition.a4.contract import (
    A4ContractError,
    A4_CONTRACT_VERSION,
    A4_GATE,
    canonical_contract_json,
    contract_sha256,
    load_contract,
    validate_contract,
)
from active_audition.a4.identity import (
    A4IdentityError,
    canonical_json,
    canonical_json_bytes,
    identity_sha256,
    sha256_bytes,
    stable_id,
)
from active_audition.a4.budget import (
    MotionCost,
    MotionCostError,
    MotionParameters,
    compute_motion_cost,
    normalize_yaw_deg,
    shortest_yaw_delta_deg,
)
from active_audition.a4.pose_sampler import (
    CandidateContract,
    PathFinderLike,
    ProbeAttemptRecord,
    SamplerContext,
    SamplerError,
    SamplerOutput,
    SampledPositionPlan,
    SampledYawPlan,
    annotate_geometry_legality,
    make_sampler_context,
    sample_source_free,
)
from active_audition.a4.records import (
    BlockRecord,
    CalibrationArtifact,
    EpisodeRecord,
    GeometryRecord,
    PoseRecord,
    RecordError,
    validate_block_record,
    validate_calibration_artifact,
    validate_episode_record,
    validate_geometry_record,
    pose_identity_payload,
    validate_pose_record,
)
from active_audition.a4.noise_segments import (
    EPISODE_ORDER_IDENTITY,
    EpisodeNoiseRequest,
    NOISE_PARENT_SCHEMA_VERSION,
    NOISE_SEGMENT_PLAN_SCHEMA_VERSION,
    NOISE_SEGMENT_PLANNER_ALGORITHM_IDENTITY,
    NOISE_SEGMENT_SCHEMA_VERSION,
    NoiseParentMetadata,
    NoiseSegmentError,
    NoiseSegmentPlan,
    NoiseSegmentPlannerParameters,
    NoiseSegmentRecord,
    SAMPLE_INDEX_CONVENTION_IDENTITY,
    SOURCE_TIME_CONVENTION_IDENTITY,
    plan_noise_segments,
)
from active_audition.a4.active_mask import (
    ACTIVE_MASK_ALGORITHM_IDENTITY,
    ACTIVE_MASK_CONTRACT_SCHEMA_VERSION,
    ACTIVE_MASK_SCHEMA_VERSION,
    ActiveMaskContract,
    ActiveMaskError,
    ActiveMaskRecord,
    build_active_mask,
)

__all__ = [
    "A4ContractError",
    "A4_CONTRACT_VERSION",
    "A4_GATE",
    "A4IdentityError",
    "CandidateContract",
    "BlockRecord",
    "CalibrationArtifact",
    "EpisodeRecord",
    "GeometryRecord",
    "PoseRecord",
    "ProbeAttemptRecord",
    "PathFinderLike",
    "RecordError",
    "SamplerContext",
    "SamplerError",
    "SamplerOutput",
    "SampledPositionPlan",
    "SampledYawPlan",
    "MotionCost",
    "MotionCostError",
    "MotionParameters",
    "annotate_geometry_legality",
    "canonical_contract_json",
    "canonical_json",
    "canonical_json_bytes",
    "contract_sha256",
    "compute_motion_cost",
    "identity_sha256",
    "load_contract",
    "make_sampler_context",
    "normalize_yaw_deg",
    "pose_identity_payload",
    "sample_source_free",
    "sha256_bytes",
    "shortest_yaw_delta_deg",
    "stable_id",
    "validate_block_record",
    "validate_calibration_artifact",
    "validate_contract",
    "validate_episode_record",
    "validate_geometry_record",
    "validate_pose_record",
    "ActiveMaskContract",
    "ActiveMaskError",
    "ActiveMaskRecord",
    "EpisodeNoiseRequest",
    "NoiseParentMetadata",
    "NoiseSegmentError",
    "NoiseSegmentPlan",
    "NoiseSegmentPlannerParameters",
    "NoiseSegmentRecord",
    "ACTIVE_MASK_ALGORITHM_IDENTITY",
    "ACTIVE_MASK_CONTRACT_SCHEMA_VERSION",
    "ACTIVE_MASK_SCHEMA_VERSION",
    "EPISODE_ORDER_IDENTITY",
    "NOISE_PARENT_SCHEMA_VERSION",
    "NOISE_SEGMENT_PLAN_SCHEMA_VERSION",
    "NOISE_SEGMENT_PLANNER_ALGORITHM_IDENTITY",
    "NOISE_SEGMENT_SCHEMA_VERSION",
    "SAMPLE_INDEX_CONVENTION_IDENTITY",
    "SOURCE_TIME_CONVENTION_IDENTITY",
    "build_active_mask",
    "plan_noise_segments",
]
